# build settings
baseurl:
markdown: kramdown
permalink: pretty

host: 0.0.0.0
port: 7008

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded

# l10n
defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/pl
    values:
      layout: default
      lang: pl
  -
    scope:
      path: _posts/ua
    values:
      layout: default
      lang: ua
  -
    scope:
      path: _posts/ru
    values:
      layout: default
      lang: ru

