defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/pl
    values:
      layout: default
      lang: pl
  -
    scope:
      path: _posts/ua
    values:
      layout: default
      lang: ua
  -
    scope:
      path: _posts/ru
    values:
      layout: default
      lang: ru

# Build settings
baseurl: ''
markdown: kramdown
permalink: pretty

port: 1115

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded
  