t:
  en:
    chess:
      ItsNotChessTable: "It's Not a Chess Table"
      ItsWar: "It's War"
      Table: 'Table'
      ChessPieces: 'Chess Pieces'
      Game: 'Game'
      Team: 'Team'
      TableConstructionAndDetails: 'Table Construction and Details'
      HowItsworks: 'How It works. Prepare the table for the game'
      Rook: 'Rook'
      Knight: 'Knight'
      Bishop: 'Bishop'
      Queen: 'Queen'
      King: 'King'
      WeAreNotChessProfessionals: 'We are not chess professionals'
      WeLikeCreateGoodDesignProducts: 'We like creating good design products'
      Contact: 'Contact Us'
      AntonPivniuk: 'Anton Pivniuk'
      IhorOrlovskyi: 'Ihor Orlovskyi'
      KyivUkraine: 'Kyiv, Ukraine'
  pl:
    chess:
      ItsNotChessTable: 'To Nie Szachy Tabela'
      ItsWar: 'To wojna'
      Table: 'Tabela'
      ChessPieces: 'Kształty'
      Game: 'Gra'
      Team: 'Zespół'
      TableConstructionAndDetails: 'Tabela Budowa i Szczegóły'
      HowItsworks: 'Jak to działa. Przygotuj stół do gry'
      Rook: 'Wieża'
      Knight: 'Skoczek'
      Bishop: 'Goniec'
      Queen: 'Hetman'
      King: 'Król'
      WeAreNotChessProfessionals: 'My nie jesteśmy profesjonaliści w szachy'
      WeLikeCreateGoodDesignProducts: 'Chcemy stworzyć dobre produkty projektowych'
      Contact: 'Kontakt'
      AntonPivniuk: 'Anton Pivniuk'
      IhorOrlovskyi: 'Ihor Orlovskyi'
      KyivUkraine: 'Kijów, Ukraina'
  ua:
    chess:
      ItsNotChessTable: 'Це не шаховий стіл'
      ItsWar: 'Це війна'
      Table: 'Стіл'
      ChessPieces: 'Фігури'
      Game: 'Гра'
      Team: 'Команда'
      TableConstructionAndDetails: 'Конструкція та елементи столу'
      HowItsworks: 'Як це працює. Приготуйте стіл для гри'
      Rook: 'Тура'
      Knight: 'Кінь'
      Bishop: 'Офіцер'
      Queen: 'Королева'
      King: 'Король'
      WeAreNotChessProfessionals: 'Ми не шахові професіонали'
      WeLikeCreateGoodDesignProducts: 'Ми обожнюємо створювати продукти з гарним дизайном'
      Contact: 'Контакти'
      AntonPivniuk: 'Антон Півнюк'
      IhorOrlovskyi: 'Ігор Орловський'
      KyivUkraine: 'Київ, Україна'
  ru:
    chess:
      ItsNotChessTable: 'Это не шахматный стол'
      ItsWar: 'Это война'
      Table: 'Стол'
      ChessPieces: 'Фигуры'
      Game: 'Игра'
      Team: 'Команда'
      TableConstructionAndDetails: 'Конструкция и элементы стола'
      HowItsworks: 'Как это работает. Приготовьте стол для игры'
      Rook: 'Ладья'
      Knight: 'Конь'
      Bishop: 'Офицер'
      Queen: 'Ферзь'
      King: 'Король'
      WeAreNotChessProfessionals: 'Мы не шахматные профессионалы'
      WeLikeCreateGoodDesignProducts: 'Мы обожаем создавать продукты с хорошим дизайном'
      Contact: 'Контакты'
      AntonPivniuk: 'Антон Пивнюк'
      IhorOrlovskyi: 'Игорь Орловский'
      KyivUkraine: 'Киев, Украина'


